### ISSUE TITLE
1

### ISSUE THREAD

**Issue by pengpeng-1572** [star2dust/mascot#1]
hello,what is this function randlim?

**Comment by star2dust** [comment]
Randomly generate points within given limitations. See
https://github.com/star2dust/Robotics-Toolbox/blob/master/rvcdlcs/src/common/randlim.m

**Comment by pengpeng-1572** [comment]
thank you for answer my question,i did not have the robotics toolbox.



---Original---
From: "Chu ***@***.***&gt;
Date: Sat, Mar 11, 2023 18:58 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [star2dust/mascot] 1 (Issue #1)




 
Randomly generate points within given limitations. See
 https://github.com/star2dust/Robotics-Toolbox/blob/master/rvcdlcs/src/common/randlim.m
